Repository TToon-main/ttoon-server, pull requests merged in 2024-04, with the labels that each got.

#6 Feature #5
  build.gradle
  src/main/java/com/server/ttoon/common/exception/handler/CustomExceptionAdvice.java
  src/main/java/com/server/ttoon/common/response/ApiResponse.java
  src/main/java/com/server/ttoon/common/response/status/ErrorStatus.java
  src/main/java/com/server/ttoon/domain/member/entity/Authority.java
  src/main/java/com/server/ttoon/domain/member/entity/Member.java
  src/main/java/com/server/ttoon/domain/member/entity/Provider.java
  src/main/java/com/server/ttoon/domain/member/repository/MemberRepository.java
  src/main/java/com/server/ttoon/security/auth/PrincipalDetails.java
  src/main/java/com/server/ttoon/security/config/JwtSecurityConfig.java
  src/main/java/com/server/ttoon/security/config/SecurityConfig.java
  src/main/java/com/server/ttoon/security/jwt/TokenProvider.java
  src/main/java/com/server/ttoon/security/jwt/dto/TokenDto.java
  src/main/java/com/server/ttoon/security/jwt/filter/JwtAccessDeniedHandler.java
  src/main/java/com/server/ttoon/security/jwt/filter/JwtAuthenticationEntryPoint.java
  src/main/java/com/server/ttoon/security/jwt/filter/JwtFilter.java
Labels: FEATURE

#10 [FEATURE] 카카오 로그인 및 회원가입 구현 (APP)
  src/main/java/com/server/ttoon/common/response/status/ErrorStatus.java
  src/main/java/com/server/ttoon/domain/member/controller/AppAuthController.java
  src/main/java/com/server/ttoon/domain/member/dto/request/AppAuthReqDto.java
  src/main/java/com/server/ttoon/domain/member/dto/response/AppJoinResDto.java
  src/main/java/com/server/ttoon/domain/member/dto/response/AppLoginResDto.java
  src/main/java/com/server/ttoon/domain/member/repository/MemberRepository.java
  src/main/java/com/server/ttoon/domain/member/service/AppAuthService.java
  src/main/java/com/server/ttoon/domain/member/service/AppAuthServiceImpl.java
Labels: FEATURE

#15 [DOCS] swagger 의존성 추가 및 설정
  build.gradle
  src/main/java/com/server/ttoon/common/config/SwaggerConfig.java
  src/main/java/com/server/ttoon/domain/member/controller/AppAuthController.java
  src/main/java/com/server/ttoon/domain/member/dto/response/AppJoinResDto.java
  src/main/java/com/server/ttoon/domain/member/service/AppAuthServiceImpl.java
  src/main/java/com/server/ttoon/security/jwt/controller/JwtController.java
Labels: DOCS

#16 [REFACTOR] 스웨거 https 적용
  src/main/java/com/server/ttoon/TToonApplication.java
Labels: REFACTOR

#19 [FEATURE] 버전 컨트롤러 구현
  src/main/java/com/server/ttoon/domain/member/controller/AppAuthController.java
Labels: FEATURE
